runs:
  using: composite
  steps:
    - name: Checkout the artifact repository files
      run: git clone --depth 1 --recursive https://github.com/${{ env.ARTIFACT_REPOSITORY }} working-directory/
      shell: bash
    - name: Create the vcpkg caching directory
      working-directory: working-directory/
      run: mkdir -p ${{ github.workspace }}/vcpkg/bincache
      shell: bash
    - name: Expose GitHub runtime
      uses: crazy-max/ghaction-github-runtime@v3
    - name: Set current HEAD SHA
      working-directory: working-directory/
      run: echo "TB_PULL_REQUEST_HEAD_SHA_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
      shell: bash
    - name: Install common dependencies
      working-directory: working-directory/
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends build-essential libxi-dev libxrandr-dev libxxf86vm-dev freeglut3-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libglm-dev pandoc ninja-build libglew-dev libfreeimage-dev libfreetype6-dev libtinyxml2-dev libassimp-dev libfuse2 qtbase5-dev libqt5svg5-dev
      shell: bash
    - name: Compile the source code
      working-directory: working-directory/
      run: ./CI-linux.sh
      shell: bash
    - name: Prepare the artifact
      working-directory: working-directory/
      run: |
        mkdir -p ${{ env.ARTIFACT_DIRECTORY_NAME }}-linux
        mv build/${{ env.ARTIFACT_NAME }}-* ${{ env.ARTIFACT_DIRECTORY_NAME }}-linux/
      shell: bash
    - name: Pack and upload the artifact
      uses: actions/upload-artifact@v4
      with:
        path: working-directory/${{ env.ARTIFACT_DIRECTORY_NAME }}-linux/
        name: ${{ env.ARTIFACT_DIRECTORY_NAME }}-binaries-linux
        if-no-files-found: error
        retention-days: 1
