inputs:
  ARTIFACT_PATH:
    required: true
  CACHE_KEY:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: ${{ inputs.CACHE_KEY }}
        path: ${{ inputs.ARTIFACT_PATH }}
