inputs:
  ARTIFACT_FILENAME:
    required: true
  CICD_OPERATING_SYSTEM_NAME:
    required: true
runs:
  using: composite
  steps:
    - name: Create the working directory
      run: |
        set -euo pipefail
        mkdir -p working-directory/
      shell: bash
    - name: "Prototype WAD: Download and cache"
      uses: ./.github/actions/_shared/download-and-cache-file
      with:
        DESTINATION_PATH: ${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}/quake/prototype-wad/
        DOWNLOAD_URL: https://www.slipseer.com/index.php?resources/prototype-wad.263/version/448/download&file=3663
        FILENAME: prototype-wad
        FILE_TYPE: zip
    - name: "Quake Palette: Download and cache"
      uses: ./.github/actions/_shared/download-and-cache-file
      with:
        DESTINATION_PATH: ${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}/quake/quake-palette/
        DOWNLOAD_URL: https://quakewiki.org/w/images/d/d2/quake_palette.zip
        FILENAME: quake-palette
        FILE_TYPE: zip
    - name: "TrenchBroom Quake Map Source: Download and cache"
      uses: ./.github/actions/_shared/download-and-cache-file
      with:
        DESTINATION_PATH: ${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}/quake/trenchbroom-quake-map-source/
        DOWNLOAD_URL: https://toolness-media.s3.amazonaws.com/quake/trenchbroom_quake_map_source.zip
        FILENAME: trenchbroom-quake-map-source
        FILE_TYPE: zip
    - name: "Digit's Developer Textures: Download and cache"
      uses: ./.github/actions/_shared/download-and-cache-file
      with:
        DESTINATION_PATH: ${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}/goldsrc/digits-developer-textures/
        DOWNLOAD_URL: https://files.gamebanana.com/mods/digits-devtex-13.rar
        FILENAME: digits-developer-textures
        FILE_TYPE: rar
