inputs:
  matrix_os:
    required: true
runs:
  using: composite
  steps:
    - name: Set the operating system name
      run: echo "PARSED_MATRIX_OS=$([[ "${{ inputs.matrix_os }}" == ubuntu* ]] && echo linux || echo "${{ inputs.matrix_os }}" | cut -d'-' -f1)" >> $GITHUB_ENV
      shell: bash
