inputs:
  ARTIFACT_FILENAME:
    required: true
  ARTIFACT_PATH:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        compression-level: 0
        if-no-files-found: error
        name: ${{ inputs.ARTIFACT_FILENAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
        retention-days: 1
