name: pack-upload-artifact
description: Packs and uploads a build artifact with minimal retention.
inputs:
  ARTIFACT_FILENAME:
    required: true
  ARTIFACT_PATH:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v7
      with:
        compression-level: 0
        if-no-files-found: error
        name: ${{ inputs.ARTIFACT_FILENAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
        retention-days: 1
