name: "Extras: Generate metadata"
runs:
  using: composite
  steps:
    - name: Create the working directory
      run: mkdir -p working-directory
      shell: bash
    - name: Create initial content
      working-directory: working-directory/
      run: |
        mkdir -p ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/
        echo "
        ### ${{ env.ARTIFACT_NAME }}
        " >> ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/METADATA.md
      shell: bash
    - name: Create Quake section
      working-directory: working-directory/
      run: |
        mkdir -p ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/
        echo "
        #### Quake
        " >> ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/METADATA.md
      shell: bash
    - name: "${{ env.EXTRA_NAME }}: Create the content"
      working-directory: working-directory/
      run: echo "- **${{ env.EXTRA_NAME }}**, ${{ env.EXTRA_AUTHOR_NAME }} [[${{ env.EXTRA_SOURCE_NAME }}](${{ env.EXTRA_DETAILS_URL }})]" >> ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/METADATA.md
      shell: bash
      env:
        EXTRA_NAME: Prototype WAD
        EXTRA_AUTHOR_NAME: Aleksander Marhall
        EXTRA_SOURCE_NAME: Slipseer
        EXTRA_DETAILS_URL: https://www.slipseer.com/index.php?resources/prototype-wad.263
    - name: "${{ env.EXTRA_NAME }}: Create the content"
      working-directory: working-directory/
      run: echo "- **${{ env.EXTRA_NAME }}**, ${{ env.EXTRA_AUTHOR_NAME }} [[${{ env.EXTRA_SOURCE_NAME }}](${{ env.EXTRA_DETAILS_URL }})]" >> ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/METADATA.md
      shell: bash
      env:
        EXTRA_NAME: Quake Palette
        EXTRA_AUTHOR_NAME: Spiney
        EXTRA_SOURCE_NAME: Quake Wiki
        EXTRA_DETAILS_URL: https://quakewiki.org/wiki/Quake_palette
    - name: "${{ env.EXTRA_NAME }}: Create the content"
      working-directory: working-directory/
      run: echo "- **${{ env.EXTRA_NAME }}**, ${{ env.EXTRA_AUTHOR_NAME }} [[${{ env.EXTRA_SOURCE_NAME }}](${{ env.EXTRA_DETAILS_URL }})]" >> ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/METADATA.md
      shell: bash
      env:
        EXTRA_NAME: TrenchBroom Quake Map Source
        EXTRA_AUTHOR_NAME: Atul Varma
        EXTRA_SOURCE_NAME: The Level Design Book
        EXTRA_DETAILS_URL: https://book.leveldesignbook.com/appendix/resources/quake
    - name: Create GoldSrc section
      working-directory: working-directory/
      run: |
        mkdir -p ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/
        echo "
        #### GoldSrc
        " >> ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/METADATA.md
      shell: bash
    - name: "${{ env.EXTRA_NAME }}: Create the content"
      working-directory: working-directory/
      run: echo "- **${{ env.EXTRA_NAME }}**, ${{ env.EXTRA_AUTHOR_NAME }} [[${{ env.EXTRA_SOURCE_NAME }}](${{ env.EXTRA_DETAILS_URL }})]" >> ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/METADATA.md
      shell: bash
      env:
        EXTRA_NAME: Digit's Developer Textures
        EXTRA_AUTHOR_NAME: Digit404
        EXTRA_SOURCE_NAME: GameBanana
        EXTRA_DETAILS_URL: https://gamebanana.com/mods/6693
    - name: Pack and upload the metadata
      uses: actions/upload-artifact@v4
      with:
        path: working-directory/${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/
        name: ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata
        if-no-files-found: error
        retention-days: 1
