name: "Windows: Build the binaries"
runs:
  using: composite
  steps:
    - name: Checkout the artifact repository files
      run: git clone --depth 1 --recursive https://github.com/${{ env.ARTIFACT_REPOSITORY }} working-directory/
      shell: bash
    - name: Set environment variables
      working-directory: working-directory/
      run: |
        $gitrev = $(git describe --always)
        $gitbranch = $(git branch --show-current)
        $ver_suffix = ("$gitbranch" -eq "master" -Or "$gitbranch" -eq "main") ? "-$gitrev" : "-$gitbranch-$gitrev"
        $platform_alt = "win64"
        $platform_short = "x64"
        $build_artifact = "${env:ARTIFACT_DIRECTORY_NAME}-windows"
        echo "VER_SUFFIX=$ver_suffix" >> ${env:GITHUB_ENV}
        echo "BUILD_ARTIFACT=$build_artifact" >> ${env:GITHUB_ENV}
        echo "BUILD_DIR=$build_artifact" >> ${env:GITHUB_ENV}
        echo "PLATFORM_ALT=$platform_alt" >> ${env:GITHUB_ENV}
        echo "PLATFORM_SHORT=$platform_short" >> ${env:GITHUB_ENV}
        echo "ForceImportBeforeCppTargets=${env:GITHUB_WORKSPACE}\Windows\VisualStudio\custom_build.props" >> ${env:GITHUB_ENV}
      shell: pwsh
    - name: Compile the source code
      working-directory: working-directory/
      run: |
        $msbuild = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | Select-Object -First 1
        & $msbuild Windows\VisualStudio\${env:ARTIFACT_DIRECTORY_NAME}.sln -property:Configuration=Release -property:Platform=x64 -maxcpucount -verbosity:minimal
        if (-not $?) { throw "Build failed" }
      shell: pwsh
    - name: Prepare the artifact
      working-directory: working-directory/
      run: |
        $compiledir = "Windows\VisualStudio\${env:BUILD_DIR}"
        $zipdir = "${env:BUILD_ARTIFACT}"
        mkdir -p $zipdir | Out-Null
        copy ${compiledir}\*.exe $zipdir
        copy ${compiledir}\*.dll $zipdir
        copy Quake\${env:ARTIFACT_DIRECTORY_NAME}.pak $zipdir
        copy Quakespasm.html $zipdir
        copy Quakespasm.txt $zipdir
        copy Quakespasm-Music.txt $zipdir
        copy LICENSE.txt $zipdir
      shell: pwsh
    - name: Pack and upload the artifact
      uses: actions/upload-artifact@v4
      with:
        path: working-directory/${{ env.ARTIFACT_DIRECTORY_NAME }}-windows/
        name: ${{ env.ARTIFACT_DIRECTORY_NAME }}-binaries-windows
        if-no-files-found: error
        retention-days: 1
