name: setup-msvc-environment
description: Initializes the MSVC developer command-line environment.
inputs:
  MSVC_VERSION:
    required: true
runs:
  using: composite
  steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: ${{ inputs.MSVC_VERSION }}
