name: "Windows: Build the binaries"
runs:
  using: composite
  steps:
    - name: Checkout the artifact repository files
      run: git clone --depth 1 --recursive https://github.com/${{ env.ARTIFACT_REPOSITORY }} working-directory/
      shell: bash
    - name: Compile the source code
      working-directory: working-directory/
      run: make windows
      shell: pwsh
    - name: Prepare the artifact
      working-directory: working-directory/
      run: |
        $zipdir = "${env:ARTIFACT_DIRECTORY_NAME}-windows"
        mkdir -p $zipdir | Out-Null
        copy *.exe $zipdir
      shell: pwsh
    - name: Pack and upload the artifact
      uses: actions/upload-artifact@v4
      with:
        path: working-directory/${{ env.ARTIFACT_DIRECTORY_NAME }}-windows/
        name: ${{ env.ARTIFACT_DIRECTORY_NAME }}-binaries-windows
        if-no-files-found: error
        retention-days: 1
