inputs:
  CICD_OPERATING_SYSTEM_NAME:
    required: true
  QT_VERSION:
    required: true
runs:
  using: composite
  steps:
    - uses: jurplel/install-qt-action@d325aaf2a8baeeda41ad0b5d39f84a6af9bcf005
      with:
        cache: true
        cache-key-prefix: qt-${{ inputs.QT_VERSION }}-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}
        version: ${{ inputs.QT_VERSION }}
