name: install-qt
description: Installs a specific Qt version with caching support.
inputs:
  CICD_OPERATING_SYSTEM_NAME:
    required: true
  QT_VERSION:
    required: true
runs:
  using: composite
  steps:
    - uses: jurplel/install-qt-action@v4
      with:
        cache: true
        cache-key-prefix: qt-${{ inputs.QT_VERSION }}-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}
        version: ${{ inputs.QT_VERSION }}
