runs:
  using: composite
  steps:
    - name: Checkout the artifact repository files
      run: git clone --depth 1 --recursive https://github.com/${{ env.ARTIFACT_REPOSITORY }} working-directory/
      shell: bash
    - name: Install Python requirements
      working-directory: working-directory/
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
      shell: bash
    - name: Compile the source code
      working-directory: working-directory/
      run: make build
      shell: bash
    - name: Prepare the artifact
      working-directory: working-directory/
      run: |
        make package
        7z x "$(find . -type f -name '${{ env.ARTIFACT_DIRECTORY_NAME }}-*-linux.zip' | head -n 1)" -y
        mv ${{ env.ARTIFACT_DIRECTORY_NAME }}-*-linux/ ${{ env.ARTIFACT_DIRECTORY_NAME }}-linux/
      shell: bash
    - name: Pack and upload the artifact
      uses: actions/upload-artifact@v4
      with:
        path: working-directory/${{ env.ARTIFACT_DIRECTORY_NAME }}-linux/
        name: ${{ env.ARTIFACT_DIRECTORY_NAME }}-binaries-linux
        if-no-files-found: error
        retention-days: 1
