inputs:
  ARTIFACT_FILENAME:
    required: true
  CICD_PROJECT_ACRONYM:
    required: true
  CICD_PROJECT_FULL_NAME:
    required: true
  CICD_PROJECT_SLUG:
    required: true
  CICD_WORKFLOW:
    required: true
  LIST_METADATA_FILES:
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/_shared/download-artifact
      with:
        ARTIFACT_FILENAME: ^.*-${{ inputs.ARTIFACT_FILENAME }}.*$
        CICD_WORKFLOW: ${{ inputs.CICD_WORKFLOW }}
    - run: |
        set -euo pipefail
        mkdir -p ${{ inputs.CICD_PROJECT_SLUG }}-release-notes/
        echo "This is a release of [${{ inputs.CICD_PROJECT_FULL_NAME }}](https://github.com/${{ github.repository_owner }}/${{ inputs.CICD_PROJECT_SLUG }}). For comprehensive details about the project and setup guidance, please [refer to the instructions](https://github.com/${{ github.repository_owner }}/${{ inputs.CICD_PROJECT_SLUG }}/wiki).

        ## Features

        The current version of **${{ inputs.CICD_PROJECT_ACRONYM }}** includes the following set of applications, tools and extras:" >> "${{ inputs.CICD_PROJECT_SLUG }}-release-notes/RELEASE_NOTES.md"
        IFS=',' read -r -a list_metadata_files <<< "${{ inputs.LIST_METADATA_FILES }}"
        for metadata_file in "${list_metadata_files[@]}"; do
          7z e -so "$metadata_file-${{ inputs.ARTIFACT_FILENAME }}.zip" METADATA.md >> "${{ inputs.CICD_PROJECT_SLUG }}-release-notes/RELEASE_NOTES.md" -y
        done
      shell: bash
