inputs:
  ARTIFACT_PATH:
    required: true
  CACHE_KEY:
    required: true
outputs:
  CACHE_HIT:
    value: ${{ steps.cache-restore.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - id: cache-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        key: ${{ inputs.CACHE_KEY }}
        path: ${{ inputs.ARTIFACT_PATH }}
