inputs:
  ARTIFACT_FILENAME:
    required: true
  ARTIFACT_REPOSITORY:
    required: true
  CICD_OPERATING_SYSTEM_NAME:
    required: true
runs:
  using: composite
  steps:
    - name: Checkout the artifact repository files
      uses: ./.github/actions/_shared/checkout-artifact-repository-files
      with:
        ARTIFACT_REPOSITORY: ${{ inputs.ARTIFACT_REPOSITORY }}
    - name: Set the current commit HEAD SHA
      uses: ./.github/actions/_shared/set-current-commit-head-sha
      with:
        CICD_WORKING_DIRECTORY: working-directory/
    - name: Restore the artifact from cache
      id: cache-restore
      uses: ./.github/actions/_shared/cache-restore
      with:
        PATH: working-directory/${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}/
        CACHE_KEY: ${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}-${{ env.GIT_CURRENT_COMMIT_HEAD_SHA }}
    - name: Set up the MSVC environment
      if: steps.cache-restore.outputs.CACHE_HIT != 'true'
      uses: ./.github/actions/_shared/setup-msvc-environment
      with:
        MSVC_VERSION: 2022
    - name: Restore pip cache
      if: steps.cache-restore.outputs.CACHE_HIT != 'true'
      id: cache-pip
      uses: ./.github/actions/_shared/cache-restore
      with:
        PATH: ~\AppData\Local\pip\Cache
        CACHE_KEY: pip-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}-${{ hashFiles('working-directory/requirements*.txt') }}
    - name: Install Python requirements
      if: steps.cache-restore.outputs.CACHE_HIT != 'true' && steps.cache-pip.outputs.CACHE_HIT != 'true'
      working-directory: working-directory/
      run: |
        $ErrorActionPreference = 'Stop'
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
      shell: pwsh
    - name: Save pip cache
      if: steps.cache-restore.outputs.CACHE_HIT != 'true' && steps.cache-pip.outputs.CACHE_HIT != 'true'
      uses: ./.github/actions/_shared/cache-save
      with:
        PATH: ~\AppData\Local\pip\Cache
        CACHE_KEY: pip-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}-${{ hashFiles('working-directory/requirements*.txt') }}
    - name: Compile the source code
      if: steps.cache-restore.outputs.CACHE_HIT != 'true'
      working-directory: working-directory/
      run: |
        $ErrorActionPreference = 'Stop'
        make build
      shell: pwsh
    - name: Prepare the artifact
      if: steps.cache-restore.outputs.CACHE_HIT != 'true'
      working-directory: working-directory/
      run: |
        $ErrorActionPreference = 'Stop'
        make package
        $zipFile = Get-ChildItem -Name "${env:ARTIFACT_FILENAME}-*-${env:CICD_OPERATING_SYSTEM_NAME}.zip" | Select-Object -First 1
        7z x "$zipFile" -y
        mv ${env:ARTIFACT_FILENAME}-*-${env:CICD_OPERATING_SYSTEM_NAME}/ ${env:ARTIFACT_FILENAME}-files-${env:CICD_OPERATING_SYSTEM_NAME}/
      env:
        ARTIFACT_FILENAME: ${{ inputs.ARTIFACT_FILENAME }}
        CICD_OPERATING_SYSTEM_NAME: ${{ inputs.CICD_OPERATING_SYSTEM_NAME }}
      shell: pwsh
    - name: Save the artifact as cache
      if: steps.cache-restore.outputs.CACHE_HIT != 'true'
      uses: ./.github/actions/_shared/cache-save
      with:
        PATH: working-directory/${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}/
        CACHE_KEY: ${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}-${{ env.GIT_CURRENT_COMMIT_HEAD_SHA }}
