name: set-current-date
description: Sets the current date in YYYYMMDD format as an environment variable.
runs:
  using: composite
  steps:
    - run: |
        set -euo pipefail
        echo "CICD_CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      shell: bash
