inputs:
  ARTIFACT_FILENAME:
    required: true
  ARTIFACT_REPOSITORY:
    required: true
  CICD_OPERATING_SYSTEM_NAME:
    required: true
runs:
  using: composite
  steps:
    - name: Checkout the artifact repository files
      uses: ./.github/actions/_shared/checkout-artifact-repository-files
      with:
        ARTIFACT_REPOSITORY: ${{ inputs.ARTIFACT_REPOSITORY }}
    - name: Set the current commit HEAD SHA
      uses: ./.github/actions/_shared/set-current-commit-head-sha
      with:
        CICD_WORKING_DIRECTORY: working-directory/
    - name: Restore the artifact from cache
      id: restore-cached-artifact
      uses: ./.github/actions/_shared/restore-artifact-cache
      with:
        ARTIFACT_PATH: working-directory/${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}/
        CACHE_KEY: ${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}-${{ env.GIT_CURRENT_COMMIT_HEAD_SHA }}
    - name: Set up the MSVC environment
      if: steps.restore-cached-artifact.outputs.CACHE_HIT != 'true'
      uses: ./.github/actions/_shared/setup-msvc-environment
      with:
        MSVC_VERSION: 2022
    - name: Install Qt
      if: steps.restore-cached-artifact.outputs.CACHE_HIT != 'true'
      uses: ./.github/actions/_shared/install-qt
      with:
        CICD_OPERATING_SYSTEM_NAME: ${{ inputs.CICD_OPERATING_SYSTEM_NAME }}
        QT_VERSION: 6.7.0
    - name: Compile the source code
      if: steps.restore-cached-artifact.outputs.CACHE_HIT != 'true'
      working-directory: working-directory/
      run: .\build-windows.ps1
      shell: pwsh
    - name: Prepare the artifact
      if: steps.restore-cached-artifact.outputs.CACHE_HIT != 'true'
      working-directory: working-directory/
      run: 7z x "build-${env:CICD_OPERATING_SYSTEM_NAME}\${env:ARTIFACT_FILENAME}-*.zip" -o"${env:ARTIFACT_FILENAME}-files-${env:CICD_OPERATING_SYSTEM_NAME}\" -y
      env:
        ARTIFACT_FILENAME: ${{ inputs.ARTIFACT_FILENAME }}
        CICD_OPERATING_SYSTEM_NAME: ${{ inputs.CICD_OPERATING_SYSTEM_NAME }}
      shell: pwsh
    - name: Save the artifact as cache
      if: steps.restore-cached-artifact.outputs.CACHE_HIT != 'true'
      uses: ./.github/actions/_shared/save-artifact-cache
      with:
        ARTIFACT_PATH: working-directory/${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}/
        CACHE_KEY: ${{ inputs.ARTIFACT_FILENAME }}-files-${{ inputs.CICD_OPERATING_SYSTEM_NAME }}-${{ env.GIT_CURRENT_COMMIT_HEAD_SHA }}
