name: "Quake CLI Tools: Build the binaries"
runs:
  using: composite
  steps:
    - name: Change the directory
      run: cd ${{ env.ARTIFACT_DIRECTORY_NAME }}-repository/
      shell: bash
    - name: "Linux: Install Python requirements"
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
      shell: bash
    - name: "Linux: Compile the source code"
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: make build
      shell: bash
    - name: "Linux: Prepare the artifact"
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        make package
        7z x "$(find . -type f -name '${{ env.ARTIFACT_DIRECTORY_NAME }}-*-linux.zip' | head -n 1)" -y
        mv ${{ env.ARTIFACT_DIRECTORY_NAME }}-*-linux/ ${{ env.ARTIFACT_DIRECTORY_NAME }}-linux/
      shell: bash
    - name: "Linux: Pack and upload the artifact"
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.ARTIFACT_DIRECTORY_NAME }}-linux/
        name: ${{ env.ARTIFACT_DIRECTORY_NAME }}-binaries-linux
        if-no-files-found: error
        retention-days: 1
    - name: "Windows: Setup MSVC environment"
      if: ${{ startsWith(matrix.os, 'windows-') }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: 2022
    - name: "Windows: Install Python requirements"
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
      shell: pwsh
    - name: "Windows: Compile the source code"
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: make build
      shell: pwsh
    - name: "Windows: Prepare the artifact"
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        make package
        $zipFile = Get-ChildItem -Name "${env:ARTIFACT_DIRECTORY_NAME}-*-windows.zip" | Select-Object -First 1
        7z x "$zipFile" -y
        mv ${env:ARTIFACT_DIRECTORY_NAME}-*-windows/ ${env:ARTIFACT_DIRECTORY_NAME}-windows/
      shell: pwsh
    - name: "Windows: Pack and upload the artifact"
      if: ${{ startsWith(matrix.os, 'windows-') }}
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.ARTIFACT_DIRECTORY_NAME }}-windows/
        name: ${{ env.ARTIFACT_DIRECTORY_NAME }}-binaries-windows
        if-no-files-found: error
        retention-days: 1
