inputs:
  ARTIFACT_REPOSITORY:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: 0
        path: working-directory/
        repository: ${{ inputs.ARTIFACT_REPOSITORY }}
        submodules: true
