name: checkout-artifact-repository-files
description: Checks out the source files of an upstream artifact repository.
inputs:
  ARTIFACT_REPOSITORY:
    required: true
  CHECKOUT_SUBMODULES:
    required: false
    default: recursive
runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        path: working-directory/
        repository: ${{ inputs.ARTIFACT_REPOSITORY }}
        submodules: ${{ inputs.CHECKOUT_SUBMODULES }}
