inputs:
  ARTIFACT_REPOSITORY:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        path: working-directory/
        submodules: true
        repository: ${{ inputs.ARTIFACT_REPOSITORY }}
