runs:
  using: composite
  steps:
    - name: Checkout the artifact repository files
      run: git clone --depth 1 --recursive https://github.com/${{ env.ARTIFACT_REPOSITORY }} working-directory/
      shell: bash
    - name: Set the latest commit details
      uses: ./.github/actions/_shared/set-latest-commit-details
      with:
        working_directory: working-directory/
    - name: Create the content
      working-directory: working-directory/
      run: |
        mkdir -p ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata
        echo "
        - **${{ env.ARTIFACT_NAME }}**, ${{ env.ARTIFACT_AUTHOR_NAME }} [[Documentation](${{ env.ARTIFACT_DOCUMENTATION_URL }})]

          > **Commit**: [${{ env.LAST_COMMIT_SHA_HASH }}](https://github.com/${{ env.ARTIFACT_REPOSITORY }}/commit/${{ env.LAST_COMMIT_SHA_HASH }}) pushed by [${{ env.LAST_COMMIT_AUTHOR_NAME }}](https://github.com/${{ env.LAST_COMMIT_LOGIN_NAME }}) on **${{ env.LAST_COMMIT_DATE }}**
          > **Message**: \`${{ env.LAST_COMMIT_MESSAGE }}\`
          > **Branch**: \`${{ env.CURRENT_BRANCH_NAME }}\`
          > **Repository**: https://github.com/${{ env.ARTIFACT_REPOSITORY }}" >> ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/METADATA.md
      shell: bash
    - name: Pack and upload the artifact
      uses: ./.github/actions/_shared/pack-upload-artifact
      with:
        path: working-directory/${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata/
        name: ${{ env.ARTIFACT_DIRECTORY_NAME }}-metadata
