name: cache-restore
description: Restores a previously saved cache by key and path.
inputs:
  CACHE_KEY:
    required: true
  PATH:
    required: true
outputs:
  CACHE_HIT:
    value: ${{ steps.cache-restore.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v5
      id: cache-restore
      with:
        key: ${{ inputs.CACHE_KEY }}
        path: ${{ inputs.PATH }}
