name: Continuous Building
on:
  schedule:
    - cron: 0 0 * * 1
  push:
    paths:
      - .github/actions/**
      - .github/workflows/**
jobs:
  generate-metadata:
    name: Generate Metadata
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: TrenchBroom
            author: Kristian Duske
            directory: trenchbroom
            repository: TrenchBroom/TrenchBroom
            website: http://kristianduske.com/trenchbroom
          - name: ericw-tools
            author: Eric Wasylishen
            directory: ericw-tools
            repository: ericwa/ericw-tools
            documentation: https://ericw-tools.readthedocs.io
          - name: Ironwail
            author: Andrei Drexler
            directory: ironwail
            repository: andrei-drexler/ironwail
            twitter: https://twitter.com/andrei_drexler
          - name: Quake CLI Tools
            author: Joshua Skelton
            directory: quake-cli-tools
            repository: joshuaskelly/quake-cli-tools
            website: https://joshua.itch.io/quake-tools
            howto: https://www.youtube.com/watch?v=zJ0RX62VYaA
          - name: goldutil
            author: Léo Peltier
            directory: goldutil
            repository: L-P/goldutil
    env:
      ARTIFACT_NAME: ${{ matrix.project.name }}
      ARTIFACT_AUTHOR_NAME: ${{ matrix.project.author || '' }}
      ARTIFACT_DIRECTORY_NAME: ${{ matrix.project.directory }}
      ARTIFACT_REPOSITORY: ${{ matrix.project.repository || '' }}
      ARTIFACT_WEBSITE_URL: ${{ matrix.project.website || '' }}
      ARTIFACT_DOCUMENTATION_URL: ${{ matrix.project.documentation || '' }}
      ARTIFACT_TWITTER_URL: ${{ matrix.project.twitter || '' }}
      ARTIFACT_HOWTO_URL: ${{ matrix.project.howto || '' }}
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "${{ env.ARTIFACT_NAME }}: Generate metadata"
        run: ./.github/actions/continuous-building/${{ env.ARTIFACT_DIRECTORY_NAME }}/generate-metadata
  build-binaries:
    name: Build Binaries
    needs: generate-metadata
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: TrenchBroom
            directory: trenchbroom
            repository: TrenchBroom/TrenchBroom
          - name: ericw-tools
            directory: ericw-tools
            repository: ericwa/ericw-tools
          - name: Ironwail
            directory: ironwail
            repository: andrei-drexler/ironwail
          - name: Quake CLI Tools
            directory: quake-cli-tools
            repository: joshuaskelly/quake-cli-tools
          - name: goldutil
            directory: goldutil
            repository: L-P/goldutil
        os: [ubuntu-22.04, windows-2022]
        tb-arch: [default-arch, x64]
        use-asan: [YES, NO]
        exclude:
          - project: TrenchBroom
            os: windows-2022
            tb-arch: default-arch
          - project: ericw-tools
            os: windows-2022
            use-asan: YES
        include:
          - project: TrenchBroom
            os: windows-2022
            tb-arch: x64
    env:
      ARTIFACT_NAME: ${{ matrix.project.name }}
      ARTIFACT_DIRECTORY_NAME: ${{ matrix.project.directory }}
      ARTIFACT_REPOSITORY: ${{ matrix.project.repository }}
      TB_ARCH: ${{ matrix.tb-arch || '' }}
      USE_ASAN: ${{ matrix.use-asan || '' }}
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "${{ env.ARTIFACT_NAME }}: Build the binaries"
        run: ./.github/actions/continuous-building/${{ env.ARTIFACT_DIRECTORY_NAME }}/build-binaries/$(echo "${{ matrix.os }}" | cut -d'-' -f1)
        shell: bash
