name: Continuous Building
on:
  schedule:
    - cron: 0 0 * * 1
  push:
    paths:
      - .github/actions/**
      - .github/workflows/**
jobs:
  trenchbroom-generate-metadata:
    name: "TrenchBroom: Generate metadata"
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_NAME: TrenchBroom
      ARTIFACT_AUTHOR_NAME: Kristian Duske
      ARTIFACT_DIRECTORY_NAME: trenchbroom
      ARTIFACT_REPOSITORY: TrenchBroom/TrenchBroom
      ARTIFACT_WEBSITE_URL: http://kristianduske.com/trenchbroom
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-trenchbroom-generate-metadata
  trenchbroom-build-binaries:
    name: "TrenchBroom: Build the binaries"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        tb-build-type: [release]
        tb-arch: [default-arch]
        exclude:
          - os: windows-2022
            tb-arch: default-arch
        include:
          - os: windows-2022
            tb-arch: x64
    env:
      TB_PULL_REQUEST_HEAD_SHA_HASH: ${{ github.event.pull_request.head.sha }}
      TB_OS_IMAGE: ${{ matrix.os }}
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      ARTIFACT_NAME: TrenchBroom
      ARTIFACT_DIRECTORY_NAME: trenchbroom
      ARTIFACT_REPOSITORY: TrenchBroom/TrenchBroom
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-trenchbroom-build-binaries
  ericw-tools-generate-metadata:
    name: "ericw-tools: Generate metadata"
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_NAME: ericw-tools
      ARTIFACT_AUTHOR_NAME: Eric Wasylishen
      ARTIFACT_DIRECTORY_NAME: ericw-tools
      ARTIFACT_REPOSITORY: ericwa/ericw-tools
      ARTIFACT_DOCUMENTATION_URL: https://ericw-tools.readthedocs.io
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-ericw-tools-generate-metadata
  ericw-tools-build-binaries:
    name: "ericw-tools: Build the binaries"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        use-asan: [NO]
        exclude:
          - os: windows-2022
            use-asan: YES
    env:
      USE_ASAN: ${{ matrix.use-asan }}
      ARTIFACT_DIRECTORY_NAME: ericw-tools
      ARTIFACT_REPOSITORY: ericwa/ericw-tools
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-ericw-tools-build-binaries
  ironwail-generate-metadata:
    name: "Ironwail: Generate metadata"
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_NAME: Ironwail
      ARTIFACT_AUTHOR_NAME: Andrei Drexler
      ARTIFACT_DIRECTORY_NAME: ironwail
      ARTIFACT_REPOSITORY: andrei-drexler/ironwail
      ARTIFACT_TWITTER_URL: https://twitter.com/andrei_drexler
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-ironwail-generate-metadata
  ironwail-build-binaries:
    name: "Ironwail: Build the binaries"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
    env:
      ARTIFACT_DIRECTORY_NAME: ironwail
      ARTIFACT_REPOSITORY: andrei-drexler/ironwail
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-ironwail-build-binaries
  quake-cli-tools-generate-metadata:
    name: "Quake CLI Tools: Generate metadata"
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_NAME: Quake CLI Tools
      ARTIFACT_AUTHOR_NAME: Joshua Skelton
      ARTIFACT_DIRECTORY_NAME: quake-cli-tools
      ARTIFACT_REPOSITORY: joshuaskelly/quake-cli-tools
      ARTIFACT_WEBSITE_URL: https://joshua.itch.io/quake-tools
      ARTIFACT_HOWTO_URL: https://www.youtube.com/watch?v=zJ0RX62VYaA
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-quake-cli-tools-generate-metadata
  quake-cli-tools-build-binaries:
    name: "Quake CLI Tools: Build the binaries"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
    env:
      ARTIFACT_DIRECTORY_NAME: quake-cli-tools
      ARTIFACT_REPOSITORY: joshuaskelly/quake-cli-tools
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-quake-cli-tools-build-binaries
  goldutil-generate-metadata:
    name: "goldutil: Generate metadata"
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_NAME: goldutil
      ARTIFACT_AUTHOR_NAME: Léo Peltier
      ARTIFACT_DIRECTORY_NAME: goldutil
      ARTIFACT_REPOSITORY: L-P/goldutil
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-goldutil-generate-metadata
  goldutil-build-binaries:
    name: "goldutil: Build the binaries"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
    env:
      ARTIFACT_DIRECTORY_NAME: goldutil
      ARTIFACT_REPOSITORY: L-P/goldutil
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-goldutil-build-binaries
  extras-generate-metadata:
    name: "Extras: Generate metadata"
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_NAME: Extras
      ARTIFACT_DIRECTORY_NAME: extras
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-extras-generate-metadata
  extras-get-files:
    name: "Extras: Get the files"
    runs-on: ubuntu-22.04
    env:
      ARTIFACT_NAME: Extras
      ARTIFACT_DIRECTORY_NAME: extras
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/continuous-building-extras-get-files
