name: Continuous Building
on:
  schedule:
    - cron: 0 0 * * 1
  push:
    paths:
      - .github/actions/**
      - .github/workflows/**
jobs:
  generate-metadata:
    name: Generate metadata
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: TrenchBroom
            author: Kristian Duske
            directory: trenchbroom
            repo: TrenchBroom/TrenchBroom
            website: http://kristianduske.com/trenchbroom
          - name: ericw-tools
            author: Eric Wasylishen
            directory: ericw-tools
            repo: ericwa/ericw-tools
            documentation: https://ericw-tools.readthedocs.io
          - name: Ironwail
            author: Andrei Drexler
            directory: ironwail
            repo: andrei-drexler/ironwail
            twitter: https://twitter.com/andrei_drexler
          - name: Quake CLI Tools
            author: Joshua Skelton
            directory: quake-cli-tools
            repo: joshuaskelly/quake-cli-tools
            website: https://joshua.itch.io/quake-tools
            howto: https://www.youtube.com/watch?v=zJ0RX62VYaA
          - name: goldutil
            author: Léo Peltier
            directory: goldutil
            repo: L-P/goldutil
    env:
      ARTIFACT_NAME: ${{ matrix.project.name }}
      ARTIFACT_AUTHOR_NAME: ${{ matrix.project.author }}
      ARTIFACT_DIRECTORY_NAME: ${{ matrix.project.directory }}
      ARTIFACT_REPOSITORY: ${{ matrix.project.repo }}
      ARTIFACT_WEBSITE_URL: ${{ matrix.project.website || '' }}
      ARTIFACT_DOCUMENTATION_URL: ${{ matrix.project.documentation || '' }}
      ARTIFACT_TWITTER_URL: ${{ matrix.project.twitter || '' }}
      ARTIFACT_HOWTO_URL: ${{ matrix.project.howto || '' }}
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ${{ matrix.project.name }}
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ./.github/actions/continuous-building/${{ matrix.project.directory }}/generate-metadata
  build-binaries:
    name: Build binaries
    needs: generate-metadata
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        project:
          - name: TrenchBroom
            directory: trenchbroom
            repo: TrenchBroom/TrenchBroom
          - name: ericw-tools
            directory: ericw-tools
            repo: ericwa/ericw-tools
          - name: Ironwail
            directory: ironwail
            repo: andrei-drexler/ironwail
          - name: Quake CLI Tools
            directory: quake-cli-tools
            repo: joshuaskelly/quake-cli-tools
          - name: goldutil
            directory: goldutil
            repo: L-P/goldutil
    env:
      ARTIFACT_NAME: ${{ matrix.project.name }}
      ARTIFACT_DIRECTORY_NAME: ${{ matrix.project.directory }}
      ARTIFACT_REPOSITORY: ${{ matrix.project.repo }}
    steps:
      - name: Checkout the local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ${{ matrix.project.name }} (${{ matrix.os }})
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ./.github/actions/continuous-building/${{ matrix.project.directory }}/build-binaries/$(echo "${{ matrix.os }}" | cut -d'-' -f1)
