name: Continuous Releasing
on:
  workflow_run:
    workflows: Continuous Packing
    types: completed
env:
  PROJECT_NAME_PREFIX: quake-leveldesign-starterkit
jobs:
  run-on-workflow-success:
    name: Check the previous workflow status
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Check the previous workflow status
        uses: ./.github/actions/_shared/check-previous-workflow-status
  release-starter-kit:
    name: Release the starter kit
    needs: run-on-workflow-success
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the local repository files
        uses: actions/checkout@v4
      - name: Set the current HEAD SHA
        run: echo "LAST_COMMIT_HEAD_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
        shell: bash
      - name: Set the current date
        uses: ./.github/actions/_shared/set-current-date
      - name: Download the packed release notes
        uses: ./.github/actions/_shared/download-artifact
        with:
          name: ^${{ env.PROJECT_NAME_PREFIX }}.*$
          workflow: continuous-packing.yml
      - name: Download the packed release notes
        uses: ./.github/actions/_shared/download-artifact
        with:
          name: ^${{ env.PROJECT_NAME_PREFIX }}-release-notes.*$
          workflow: continuous-packing.yml
      - name: Unpack the release notes
        run: |
          file=$(find . -type f -name "${{ env.PROJECT_NAME_PREFIX }}-release-notes-*.zip" | head -n 1)
          7z x "$file" -o"${{ env.PROJECT_NAME_PREFIX }}/"
        shell: bash
      - name: Release the starter kit
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          makeLatest: true
          artifacts: ${{ env.PROJECT_NAME_PREFIX }}-*-windows.zip,${{ env.PROJECT_NAME_PREFIX }}-*-linux.zip
          name: QLDSK v${{ env.CURRENT_DATE }} (${{ env.LAST_COMMIT_HEAD_SHA }})
          tag: v${{ env.CURRENT_DATE }}-${{ env.LAST_COMMIT_HEAD_SHA }}
          bodyFile: ${{ env.PROJECT_NAME_PREFIX }}/RELEASE_NOTES.md
